// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wilson_Futbol_5.Infraestructura.Persistencia;

#nullable disable

namespace Wilson_Futbol_5.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(WilsonDbContext))]
    [Migration("20260717162604_CrearModeloInicialPostgres")]
    partial class CrearModeloInicialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Cancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Canchas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "Wilson Futbol 5"
                        });
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TelefonoCliente");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.ConfiguracionNegocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AliasTransferencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CantidadJugadoresPorTurno")
                        .HasColumnType("integer");

                    b.Property<int>("DuracionCumpleaniosMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("DuracionTurnoNormalMinutos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorasAnticipacionCancelacion")
                        .HasColumnType("integer");

                    b.Property<int>("HorasAnticipacionRecordatorio")
                        .HasColumnType("integer");

                    b.Property<string>("MensajePagoReserva")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("MinutosEsperaReserva")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoSena")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("NombreTitularTransferencia")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("PrecioPorPersona")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorMultaInasistencia")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesNegocio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AliasTransferencia = "wilson.futbol5",
                            CantidadJugadoresPorTurno = 10,
                            DuracionCumpleaniosMinutos = 180,
                            DuracionTurnoNormalMinutos = 60,
                            FechaActualizacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorasAnticipacionCancelacion = 2,
                            HorasAnticipacionRecordatorio = 4,
                            MensajePagoReserva = "Para confirmar la reserva, transferi la seña y envia el comprobante al dueño.",
                            MinutosEsperaReserva = 30,
                            MontoSena = 25000m,
                            NombreTitularTransferencia = "Wilson Futbol 5",
                            PrecioPorPersona = 5000m,
                            ValorMultaInasistencia = 0m
                        });
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.CredencialAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashClave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SaltClave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CredencialesAdmin", (string)null);
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.ExcepcionHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Abierto")
                        .HasColumnType("boolean");

                    b.Property<int>("CanchaId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraApertura")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("HoraCierre")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId", "FechaDesde", "FechaHasta")
                        .IsUnique();

                    b.ToTable("ExcepcionesHorario", (string)null);
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.HorarioAtencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CanchaId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraApertura")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraCierre")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId", "DiaSemana");

                    b.ToTable("HorariosAtencion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CanchaId = 1,
                            DiaSemana = 1,
                            HoraApertura = new TimeOnly(18, 0, 0),
                            HoraCierre = new TimeOnly(23, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CanchaId = 1,
                            DiaSemana = 2,
                            HoraApertura = new TimeOnly(18, 0, 0),
                            HoraCierre = new TimeOnly(23, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CanchaId = 1,
                            DiaSemana = 3,
                            HoraApertura = new TimeOnly(18, 0, 0),
                            HoraCierre = new TimeOnly(23, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CanchaId = 1,
                            DiaSemana = 4,
                            HoraApertura = new TimeOnly(18, 0, 0),
                            HoraCierre = new TimeOnly(23, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CanchaId = 1,
                            DiaSemana = 5,
                            HoraApertura = new TimeOnly(18, 0, 0),
                            HoraCierre = new TimeOnly(23, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CanchaId = 1,
                            DiaSemana = 6,
                            HoraApertura = new TimeOnly(18, 0, 0),
                            HoraCierre = new TimeOnly(23, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CanchaId = 1,
                            DiaSemana = 0,
                            HoraApertura = new TimeOnly(18, 0, 0),
                            HoraCierre = new TimeOnly(23, 0, 0)
                        });
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.NotificacionWhatsApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoNotificacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEnviada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TelefonoDestino")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TipoNotificacion")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("TurnoId");

                    b.HasIndex("EstadoNotificacion", "FechaProgramada");

                    b.ToTable("NotificacionesWhatsApp", (string)null);
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Penalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoPenalizacion")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TurnoId")
                        .IsUnique();

                    b.ToTable("Penalizaciones", (string)null);
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.SesionAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("HashToken")
                        .IsUnique();

                    b.HasIndex("Activa", "FechaExpiracion");

                    b.ToTable("SesionesAdmin", (string)null);
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CanchaId")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadJugadores")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoTurno")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaVencimientoReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoSena")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MotivoCancelacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("PrecioPorPersonaAlReservar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrecioTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TipoTurno")
                        .HasColumnType("integer");

                    b.Property<string>("TokenCancelacion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TokenCancelacion")
                        .IsUnique();

                    b.HasIndex("CanchaId", "FechaHoraInicio", "FechaHoraFin");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.TurnoFijo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CanchaId")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaHasta")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Observacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("CanchaId", "DiaSemana", "HoraInicio", "HoraFin", "Activo");

                    b.ToTable("TurnosFijos", (string)null);
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.ExcepcionHorario", b =>
                {
                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.HorarioAtencion", b =>
                {
                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Cancha", "Cancha")
                        .WithMany("HorariosAtencion")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.NotificacionWhatsApp", b =>
                {
                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Turno", "Turno")
                        .WithMany("NotificacionesWhatsApp")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Penalizacion", b =>
                {
                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("Penalizaciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Turno", "Turno")
                        .WithOne("Penalizacion")
                        .HasForeignKey("Wilson_Futbol_5.Dominio.Entidades.Penalizacion", "TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Turno", b =>
                {
                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Cancha", "Cancha")
                        .WithMany("Turnos")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("Turnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.TurnoFijo", b =>
                {
                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Cancha", "Cancha")
                        .WithMany("TurnosFijos")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wilson_Futbol_5.Dominio.Entidades.Cliente", "Cliente")
                        .WithMany("TurnosFijos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Cancha", b =>
                {
                    b.Navigation("HorariosAtencion");

                    b.Navigation("Turnos");

                    b.Navigation("TurnosFijos");
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Cliente", b =>
                {
                    b.Navigation("Penalizaciones");

                    b.Navigation("Turnos");

                    b.Navigation("TurnosFijos");
                });

            modelBuilder.Entity("Wilson_Futbol_5.Dominio.Entidades.Turno", b =>
                {
                    b.Navigation("NotificacionesWhatsApp");

                    b.Navigation("Penalizacion");
                });
#pragma warning restore 612, 618
        }
    }
}
